name: crunchiest_chests
main: com.crunchiest.CrunchiestChests
version: 0.0.1
api-version: 1.15
commands:
  make-chest:
    definition: Takes the first block the player is looking at within 200 blocks and instances it as a new Treasure Chest with per player contents of whatever is inside. If an argument is passed it is set as the name of the chest which players see when opening it.
    usage: /<command>
    aliases: [chest-make,make-chest,makechest]
  delete-chest:
    definition: Takes the first block the player is looking at within 200 blocks and, if it is a Treasure Chest, turns it back to normal and deletes the associated config file.
    usage: /<command>
    aliases: [chest-delete,delete-chest,deletechest]
permissions:
  chest-controls:
    description: Allows user to access all commands in this plugin, facilitiating creation, destruction, or modification of Treasure Chests.